### ISSUE TITLE
Plugin under development yet?

### ISSUE THREAD

**Issue by mmcarlos82** [DAXGRID/open-ftth-qgis-plugin#29]
Hi, I would like to know if plugin can be installed as especified at the main explanation or is still under devepolment. I tried to use it in QGIS and does not work.
Further details would be helpfull.

Thanks in advanced!
Carlos

**Comment by runeanielsen** [comment]
Hi Carlos,

Thank you, for your interest in the project, it is currently under development and is not stable and is missing quite a bit of features. The whole project is quite big and is made to work together as one big solution, so the plugin won't work on its own.

All the code is open-source where most of it is under the MIT license, so you can look at it and try it out if you want. To get up and running you can take a look at the Kubernetes helm chart https://github.com/DAXGRID/open-ftth-chart.

// Rune
